# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('feffery_antd_charts/package-info.json', 'feffery_antd_charts'),
	('feffery_antd_charts/metadata.json', 'feffery_antd_charts'),
	('feffery_antd_charts/feffery_antd_charts.min.js', 'feffery_antd_charts'),
	('feffery_antd_charts/async-plots.js', 'feffery_antd_charts'),
	('feffery_antd_charts/async-graphs.js', 'feffery_antd_charts'),
	
	('feffery_antd_components/package-info.json', 'feffery_antd_components'),
	('feffery_antd_components/metadata.json', 'feffery_antd_components'),
	('feffery_antd_components/feffery_antd_components.min.js', 'feffery_antd_components'),
	('feffery_antd_components/async-upload.js', 'feffery_antd_components'),
	('feffery_antd_components/async-antd_table.js', 'feffery_antd_components'),
	('feffery_antd_components/async-data_display.js', 'feffery_antd_components'),
	('feffery_antd_components/async-data_entry.js', 'feffery_antd_components'),
	
	('feffery_utils_components/package-info.json', 'feffery_utils_components'),
	('feffery_utils_components/metadata.json', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_animated_3d_background_p5.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_animated_3d_background_three.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_animated_image.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_aplayer.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_auto_animate.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_auto_fit.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_burger.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_captcha.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_color_pickers.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_dom2image.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_dplayer.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_emoji_picker.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_excel_preview.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_extra_spinner.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_fancy_button.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_grid.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_http_requests.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_image_cropper.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_json_viewer.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_local_large_storage.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_markdown_editor.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_motion.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_music_player.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_photo_sphere_viewer.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_resizable.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_rich_text_editor.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_rnd.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_seamless_scroll.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_shortcut_panel.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_slider_captcha.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_sortable.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_vditor.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-feffery_word_preview.js', 'feffery_utils_components'),
    ('feffery_utils_components/async-fuc-shared.js', 'feffery_utils_components'),
    ('feffery_utils_components/feffery_utils_components.min.js', 'feffery_utils_components'),
    ('feffery_utils_components/metadata.json', 'feffery_utils_components'),
    ('feffery_utils_components/package-info.json', 'feffery_utils_components'),
    


    ('assets', 'assets'),

	],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='billsys v0.2',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['billsys.ico'],
)
